from __future__ import annotations

from pathlib import Path
from typing import Any
import json
import re

from .build_plan import create_build_plan
from .io_utils import atomic_write_json


def prepare_build_workspace(
    device_id: str,
    firmware_ref: str,
    devices_path: str | Path,
    discovery_path: str | Path,
    profile_paths: list[str | Path],
    klipper_path: str | None,
    kalico_path: str | None,
    build_root: str | Path = "builds",
    artifact_root: str | Path = "artifacts",
    can_bitrate: str = "1000000",
) -> dict[str, Any]:
    plan = create_build_plan(
        device_id=device_id,
        firmware_ref=firmware_ref,
        devices_path=devices_path,
        discovery_path=discovery_path,
        profile_paths=profile_paths,
        klipper_path=klipper_path,
        kalico_path=kalico_path,
        can_bitrate=can_bitrate,
    )

    build_dir = (Path(build_root).expanduser() / device_id / sanitize_path_part(firmware_ref)).resolve()
    artifact_dir = Path(artifact_root).expanduser().resolve()
    build_dir.mkdir(parents=True, exist_ok=True)
    artifact_dir.mkdir(parents=True, exist_ok=True)

    config_text = generate_klipper_dot_config(plan["profile"]["build"])
    build_config_name = plan.get("build_config", {}).get("name") or device_id
    config_path = build_dir / f"config.{sanitize_path_part(str(build_config_name))}"
    build_json_path = build_dir / "build.json"

    config_path.write_text(config_text, encoding="utf-8")
    atomic_write_json(build_json_path, plan)

    source_config_copy = build_dir / "profile-build.json"
    atomic_write_json(source_config_copy, plan["profile"]["build"])

    return {
        **plan,
        "action": "prepare_build",
        "prepared": True,
        "workspace": {
            "build_dir": str(build_dir),
            "build_config_name": str(build_config_name),
            "config": str(config_path),
            "build_json": str(build_json_path),
            "profile_build_json": str(source_config_copy),
            "artifact_dir": str(artifact_dir),
        },
        "next_commands": [
            f"make -C {plan['firmware_source']['path']} clean KCONFIG_CONFIG={config_path}",
            f"make -C {plan['firmware_source']['path']} olddefconfig KCONFIG_CONFIG={config_path}",
            f"make -C {plan['firmware_source']['path']} KCONFIG_CONFIG={config_path}",
            f"cp {plan['firmware_source']['path']}/out/klipper.bin {plan['outputs']['artifact']}",
        ],
    }


def generate_klipper_dot_config(build: dict[str, Any]) -> str:
    architecture = str(build.get("architecture", "")).lower()
    processor = str(build.get("processor", ""))
    communication = str(build.get("communication", "")).lower()

    lines = [
        "# Auto-generated by MCU Update Manager",
        "# Review before building firmware.",
    ]

    if architecture == "stm32":
        lines.append("CONFIG_MACH_STM32=y")
    if architecture == "rp2040":
        lines.extend(
            [
                "CONFIG_MACH_RPXXXX=y",
                "CONFIG_MACH_RP2040=y",
            ]
        )

    processor_symbols = {
        "STM32F072": "CONFIG_MACH_STM32F072=y",
        "STM32F103": "CONFIG_MACH_STM32F103=y",
        "STM32F405": "CONFIG_MACH_STM32F405=y",
        "STM32F407": "CONFIG_MACH_STM32F407=y",
        "STM32F429": "CONFIG_MACH_STM32F429=y",
        "STM32F446": "CONFIG_MACH_STM32F446=y",
        "STM32G0B1": "CONFIG_MACH_STM32G0B1=y",
        "STM32H723": "CONFIG_MACH_STM32H723=y",
        "STM32H743": "CONFIG_MACH_STM32H743=y",
    }
    if processor in processor_symbols:
        lines.append(processor_symbols[processor])

    if architecture == "stm32" and build.get("clock_reference"):
        append_unique(lines, "CONFIG_LOW_LEVEL_OPTIONS=y")

    bootloader_offset = build.get("bootloader_offset") or build.get("application_start_offset")
    offset_symbols = {
        "8KiB": "CONFIG_STM32_FLASH_START_2000=y",
        "16KiB": "CONFIG_STM32_FLASH_START_4000=y",
        "32KiB": "CONFIG_STM32_FLASH_START_8000=y",
        "64KiB": "CONFIG_STM32_FLASH_START_10000=y",
        "128KiB": "CONFIG_STM32_FLASH_START_20000=y",
        "No bootloader": "CONFIG_STM32_FLASH_START_0000=y",
    }
    if architecture == "stm32" and bootloader_offset in offset_symbols:
        lines.append(offset_symbols[bootloader_offset])
    if architecture == "rp2040" and bootloader_offset == "16KiB":
        lines.append("CONFIG_RPXXXX_FLASH_START_4000=y")
    if architecture == "rp2040" and bootloader_offset == "No bootloader":
        lines.append("CONFIG_RPXXXX_FLASH_START_0100=y")

    if build.get("clock_reference") == "8MHz crystal":
        lines.append("CONFIG_STM32_CLOCK_REF_8M=y")
    if build.get("clock_reference") == "12MHz crystal":
        lines.append("CONFIG_STM32_CLOCK_REF_12M=y")
    if build.get("clock_reference") == "25MHz crystal":
        lines.append("CONFIG_STM32_CLOCK_REF_25M=y")

    if communication == "usb_to_canbus_bridge":
        if architecture == "stm32" and build.get("usb_pins") == "PA11/PA12":
            lines.append("CONFIG_STM32_USBCANBUS_PA11_PA12=y")
        if architecture == "rp2040":
            lines.append("CONFIG_RPXXXX_USBCANBUS=y")
    elif communication == "usb":
        if architecture == "rp2040":
            lines.append("CONFIG_RPXXXX_USB=y")
        else:
            lines.extend(["CONFIG_USB=y", "CONFIG_USBSERIAL=y"])
        if architecture == "stm32" and build.get("usb_pins") == "PA11/PA12":
            lines.append("CONFIG_STM32_USB_PA11_PA12=y")

    if communication in {"canbus", "usb_to_canbus_bridge"}:
        if architecture == "rp2040":
            can_lines = rp2040_can_lines(build)
            if communication == "canbus":
                lines.append("CONFIG_RPXXXX_CANBUS=y")
        else:
            can_pin_symbol = stm32_can_pin_symbol(
                build.get("can_rx_pin"),
                build.get("can_tx_pin"),
                usb_to_canbus_bridge=communication == "usb_to_canbus_bridge",
            )
            if can_pin_symbol.startswith("CONFIG_STM32_MMENU_"):
                append_unique(lines, "CONFIG_LOW_LEVEL_OPTIONS=y")
            can_lines = [can_pin_symbol + "=y"]
        if communication == "usb_to_canbus_bridge":
            lines.append("CONFIG_USBCANBUS=y")
        lines.extend(
            [
                *can_lines,
                "CONFIG_CAN_UUID_USE_CHIPID=y",
                f"CONFIG_CANBUS_FREQUENCY={build.get('can_bitrate', '1000000')}",
            ]
        )

    gpio = build.get("gpio_pins_on_startup")
    if gpio is not None:
        lines.append(f"CONFIG_INITIAL_PINS=\"{gpio}\"")

    for option in build.get("kconfig_overrides", []):
        option_text = str(option).strip()
        if option_text and option_text not in lines:
            lines.append(option_text)

    return "\n".join(lines) + "\n"


def append_unique(lines: list[str], line: str) -> None:
    if line not in lines:
        lines.append(line)


def rp2040_can_lines(build: dict[str, Any]) -> list[str]:
    rx_gpio = str(build.get("can_rx_gpio") or build.get("can_rx_pin") or "")
    tx_gpio = str(build.get("can_tx_gpio") or build.get("can_tx_pin") or "")
    if not re.fullmatch(r"gpio(?:[0-9]|[12][0-9])", rx_gpio) or not re.fullmatch(r"gpio(?:[0-9]|[12][0-9])", tx_gpio) or rx_gpio == tx_gpio:
        raise ValueError(f"Unsupported RP2040 CAN pin pair: RX={rx_gpio}, TX={tx_gpio}")
    return [
        f"CONFIG_RPXXXX_CANBUS_GPIO_RX={rx_gpio.removeprefix('gpio')}",
        f"CONFIG_RPXXXX_CANBUS_GPIO_TX={tx_gpio.removeprefix('gpio')}",
    ]


def stm32_can_pin_symbol(rx_pin: Any, tx_pin: Any, *, usb_to_canbus_bridge: bool = False) -> str:
    pin_pair = (str(rx_pin), str(tx_pin))
    menu_symbols = {
        ("PA11", "PA12"): "CONFIG_STM32_CANBUS_PA11_PA12",
        ("PA11", "PB9"): "CONFIG_STM32_CANBUS_PA11_PB9",
        ("PB8", "PB9"): "CONFIG_STM32_MMENU_CANBUS_PB8_PB9",
        ("PI9", "PH13"): "CONFIG_STM32_MMENU_CANBUS_PI9_PH13",
        ("PB5", "PB6"): "CONFIG_STM32_MMENU_CANBUS_PB5_PB6",
        ("PB12", "PB13"): "CONFIG_STM32_MMENU_CANBUS_PB12_PB13",
        ("PD0", "PD1"): "CONFIG_STM32_MMENU_CANBUS_PD0_PD1",
        ("PB0", "PB1"): "CONFIG_STM32_MMENU_CANBUS_PB0_PB1",
        ("PD12", "PD13"): "CONFIG_STM32_MMENU_CANBUS_PD12_PD13",
        ("PC2", "PC3"): "CONFIG_STM32_MMENU_CANBUS_PC2_PC3",
        ("PH13", "PH14"): "CONFIG_STM32_MMENU_CANBUS_PH13_PH14",
    }
    bridge_symbols = {
        ("PB8", "PB9"): "CONFIG_STM32_CMENU_CANBUS_PB8_PB9",
        ("PI9", "PH13"): "CONFIG_STM32_CMENU_CANBUS_PI9_PH13",
        ("PB5", "PB6"): "CONFIG_STM32_CMENU_CANBUS_PB5_PB6",
        ("PB12", "PB13"): "CONFIG_STM32_CMENU_CANBUS_PB12_PB13",
        ("PD0", "PD1"): "CONFIG_STM32_CMENU_CANBUS_PD0_PD1",
        ("PB0", "PB1"): "CONFIG_STM32_CMENU_CANBUS_PB0_PB1",
        ("PD12", "PD13"): "CONFIG_STM32_CMENU_CANBUS_PD12_PD13",
        ("PC2", "PC3"): "CONFIG_STM32_CMENU_CANBUS_PC2_PC3",
        ("PH13", "PH14"): "CONFIG_STM32_CMENU_CANBUS_PH13_PH14",
    }
    symbols = bridge_symbols if usb_to_canbus_bridge else menu_symbols
    if pin_pair not in symbols:
        raise ValueError(f"Unsupported STM32 CAN pin pair: RX={rx_pin}, TX={tx_pin}")
    return symbols[pin_pair]


def sanitize_path_part(value: str) -> str:
    return value.replace("/", "_").replace("\\", "_").replace(":", "_")
